GET http://localhost:5000/api/cities 

### 
GET http://localhost:5000/api/cities/2 

### 

POST http://localhost:5000/api/cities 
Content-Type: application/json 

{ 
    "city": "Luanda", 
    "country": "Angola"
}

###

DELETE http://localhost:5000/api/cities/1
